name: Deploy AWS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '16.x'
          
      - run: yarn install
      - run: yarn build
      
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
    
    steps:
      - run: sudo apt install openssh-client
      - run: eval $(ssh-agent -s)
      - run: echo '$AWS_KEY' | tr -d '\r' | ssh-add -
      - run: mkdir -p ~/.ssh
      - run: chmod 700 ~/.ssh
      - run: ssh -o StrictHostKeyChecking=no ubuntu@44.203.55.154 "cd ~/public_html && rm -rf static/"
      - run: scp -r -o StrictHostKeyChecking=no build/* ubuntu@44.203.55.154:~/public_html
      
